# Generated by Django 3.1.7 on 2021-03-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210303_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_codee',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
