# Generated by Django 3.1.7 on 2021-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
